"""add position number

Revision ID: 1cd0f313040b
Revises: 99da321fde79
Create Date: 2026-02-08 12:29:41.721099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd0f313040b'
down_revision: Union[str, Sequence[str], None] = '99da321fde79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_positions', sa.Column('position_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_positions', 'position_number')
    # ### end Alembic commands ###
