"""remove quanitity and price and total

Revision ID: 99da321fde79
Revises: 6798e35b4f21
Create Date: 2026-02-08 09:10:47.873588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99da321fde79'
down_revision: Union[str, Sequence[str], None] = '6798e35b4f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_positions', 'price_value')
    op.drop_column('order_positions', 'quantity_confidence')
    op.drop_column('order_positions', 'quantity_value')
    op.drop_column('order_positions', 'price_confidence')
    op.drop_column('order_positions', 'total_confidence')
    op.drop_column('order_positions', 'total_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_positions', sa.Column('total_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('order_positions', sa.Column('total_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('order_positions', sa.Column('price_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('order_positions', sa.Column('quantity_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('order_positions', sa.Column('quantity_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('order_positions', sa.Column('price_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
